---
  verbose: yes
  services:
    - name: last
      type: Int
      config: -1
  nodes:
    - name: market
      type: MarketStreamer
      source: yes
      inject:
        - last
      config:
        exchange: btcchina
        pair: BTC/CNY
        timeout: 10
    - name: vma
      type: VMA
      input:
        - market
      config:
        volume: 30
    - name: _
      type: Logger
      input:
        - market
        - vma
      config:
        name: vma
